# Generated by Django 3.1.7 on 2021-03-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210315_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
