# Generated by Django 3.1.7 on 2021-03-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210304_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title_photo',
            field=models.ImageField(default='img/blog/no_image.png', null=True, upload_to='img/blog_article'),
        ),
    ]
