# Generated by Django 3.1.7 on 2021-03-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='img/books/cover-img/no_image.png', null=True, upload_to='img/books/cover-img'),
        ),
    ]
