# Generated by Django 3.1.7 on 2021-03-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
