# Generated by Django 3.1.7 on 2021-03-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210321_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='translated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
