# Generated by Django 3.1.7 on 2021-03-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, unique=True)),
                ('present_value_1', models.IntegerField(default=0, null=True)),
                ('present_value_2', models.IntegerField(default=0, null=True)),
                ('present_value_3', models.IntegerField(default=0, null=True)),
                ('present_value_4', models.IntegerField(default=0, null=True)),
                ('present_value_5', models.IntegerField(default=0, null=True)),
                ('present_value_6', models.IntegerField(default=0, null=True)),
                ('future_value_1', models.IntegerField(default=0, null=True)),
                ('future_value_2', models.IntegerField(default=0, null=True)),
                ('future_value_3', models.IntegerField(default=0, null=True)),
                ('future_value_4', models.IntegerField(default=0, null=True)),
                ('future_value_5', models.IntegerField(default=0, null=True)),
                ('future_value_6', models.IntegerField(default=0, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
