# Generated by Django 3.1.7 on 2021-03-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='future_value_1',
            new_name='fv1',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='future_value_2',
            new_name='fv2',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='future_value_3',
            new_name='fv3',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='future_value_4',
            new_name='fv4',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='future_value_5',
            new_name='fv5',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='future_value_6',
            new_name='fv6',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='present_value_1',
            new_name='pv1',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='present_value_2',
            new_name='pv2',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='present_value_3',
            new_name='pv3',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='present_value_4',
            new_name='pv4',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='present_value_5',
            new_name='pv5',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='present_value_6',
            new_name='pv6',
        ),
    ]
