# Generated by Django 3.1.7 on 2021-03-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0002_auto_20210306_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='title_photo',
            field=models.ImageField(default='img/blog/no_pic.png', null=True, upload_to='img/blog_rich'),
        ),
    ]
