# Generated by Django 3.1.7 on 2021-03-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0004_auto_20210306_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
