# Generated by Django 3.1.7 on 2021-03-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0006_auto_20210306_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
