# Generated by Django 3.1.7 on 2021-03-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0007_asset_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='fv10',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='fv7',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='fv8',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='fv9',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='pv10',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='pv7',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='pv8',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='pv9',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
