# Generated by Django 3.1.7 on 2021-03-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0008_auto_20210306_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_krw', models.IntegerField()),
                ('cash_usd', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
