# Generated by Django 3.1.7 on 2021-03-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0009_cashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
