# Generated by Django 3.1.7 on 2021-03-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0010_cashflow_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflowcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('nation', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('code_or_ticker', models.CharField(max_length=10, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rich.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Tradecategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stocktrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('krw_usd_rate', models.DecimalField(decimal_places=2, default=1100, max_digits=7, null=True)),
                ('io', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rich.tradecategory')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rich.stock')),
            ],
        ),
        migrations.AddField(
            model_name='cashflow',
            name='io',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rich.cashflowcategory'),
        ),
    ]
