# Generated by Django 3.1.7 on 2021-03-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0011_auto_20210306_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='memo',
            field=models.TextField(default='-', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='split_cons',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
