# Generated by Django 3.1.7 on 2021-03-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0012_auto_20210306_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='cash_krw',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='cash_usd',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rich.currency'),
        ),
    ]
