# Generated by Django 3.1.7 on 2021-03-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0013_auto_20210306_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='current_price',
        ),
    ]
