# Generated by Django 3.1.7 on 2021-03-06 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0014_remove_stock_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='fv1',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='fv10',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='fv2',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='fv3',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='fv4',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='fv5',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='fv6',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='fv7',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='fv8',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='fv9',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='pv1',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='pv10',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='pv2',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='pv3',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='pv4',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='pv5',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='pv6',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='pv7',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='pv8',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='pv9',
        ),
        migrations.AddField(
            model_name='asset',
            name='a10_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a10', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a10_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a11_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a11', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a11_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a12_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a12', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a12_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a13_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a13', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a13_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a14_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a14', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a14_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a15_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a15', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a15_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a16_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a16', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a16_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a17_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a17', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a17_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a18_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a18', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a18_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a19_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a19', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a19_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a1_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a1', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a1_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a20_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a20', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a20_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a21_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a21', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a21_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a22_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a22', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a22_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a23_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a23', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a23_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a24_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a24', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a24_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a25_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a25', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a25_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a26_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a26', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a26_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a27_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a27', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a27_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a28_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a28', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a28_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a29_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a29', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a29_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a2_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a2', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a2_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a30_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a30', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a30_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a31_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a31', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a31_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a32_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a32', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a32_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a33_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a33', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a33_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a34_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a34', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a34_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a35_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a35', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a35_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a36_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a36', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a36_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a37_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a37', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a37_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a38_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a38', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a38_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a39_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a39', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a39_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a3_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a3', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a3_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a40_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a40', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a40_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a41_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a41', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a41_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a42_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a42', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a42_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a43_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a43', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a43_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a44_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a44', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a44_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a45_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a45', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a45_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a46_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a46', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a46_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a47_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a47', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a47_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a48_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a48', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a48_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a49_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a49', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a49_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a4_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a4', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a4_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a50_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a50', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a50_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a5_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a5', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a5_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a6_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a6', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a6_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a7_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a7', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a7_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a8_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a8', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a8_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='a9_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a9', to='rich.stock'),
        ),
        migrations.AddField(
            model_name='asset',
            name='a9_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
