# Generated by Django 3.1.7 on 2021-03-06 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0015_auto_20210306_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='a1_name',
            field=models.ForeignKey(default='삼성전자', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a1', to='rich.stock'),
        ),
    ]
