# Generated by Django 3.1.7 on 2021-03-06 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0019_auto_20210306_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='a1_name',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a1', to='rich.stock'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='a2_name',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a2', to='rich.stock'),
        ),
    ]
