# Generated by Django 3.1.7 on 2021-03-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0020_auto_20210306_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='currency',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='cash_krw',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='cash_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
