# Generated by Django 3.1.7 on 2021-03-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0023_auto_20210306_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
    ]
