# Generated by Django 3.1.7 on 2021-03-07 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0024_auto_20210306_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-date']},
        ),
    ]
