# Generated by Django 3.1.7 on 2021-03-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0025_auto_20210307_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktrade',
            name='io',
            field=models.IntegerField(choices=[(1, '매수'), (-1, '매도')], null=True),
        ),
    ]
