# Generated by Django 3.1.7 on 2021-03-07 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0026_auto_20210307_0224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tradecategory',
        ),
    ]
