# Generated by Django 3.1.7 on 2021-03-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0027_delete_tradecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='io',
            field=models.IntegerField(choices=[(1, '입금'), (-1, '출금'), (1, '배당 입금'), (1, '환전')], null=True),
        ),
    ]
