# Generated by Django 3.1.7 on 2021-03-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0028_auto_20210307_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='io',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rich.cashflowcategory'),
        ),
    ]
