# Generated by Django 3.1.7 on 2021-03-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0029_auto_20210307_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowcategory',
            name='constant',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
