# Generated by Django 3.1.7 on 2021-03-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0030_cashflowcategory_constant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('cash_sell', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('cash_buy', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('cash_buy_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buy_currency', to='rich.currency')),
                ('cash_sell_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sell_currency', to='rich.currency')),
            ],
        ),
    ]
