# Generated by Django 3.1.7 on 2021-03-08 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0031_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktrade',
            name='price',
        ),
        migrations.AddField(
            model_name='stocktrade',
            name='currency_trade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rich.currency'),
        ),
        migrations.AddField(
            model_name='stocktrade',
            name='price_std',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktrade',
            name='price_trade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stocktrade',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
