# Generated by Django 3.1.7 on 2021-03-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0033_auto_20210309_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('nick', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
    ]
