# Generated by Django 3.1.7 on 2021-03-09 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0034_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rich.account'),
        ),
    ]
