# Generated by Django 3.1.7 on 2021-03-09 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0036_stocktradecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktrade',
            name='io',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rich.stocktradecategory'),
        ),
    ]
