# Generated by Django 3.1.7 on 2021-03-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0038_stocktrade_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktrade',
            old_name='price_trade',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='stocktrade',
            name='currency_trade',
        ),
        migrations.RemoveField(
            model_name='stocktrade',
            name='krw_usd_rate',
        ),
        migrations.RemoveField(
            model_name='stocktrade',
            name='price_std',
        ),
    ]
