# Generated by Django 3.1.7 on 2021-03-09 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0040_auto_20210309_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktrade',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rich.currency'),
        ),
    ]
